[project]
name = "vis-r"
version = "0.0.1"
dependencies = [
    "numpy", "scipy", "matplotlib", "arviz", "corner",
    "frank", "cmdstanpy", "emcee", "multiprocess"
]

[project.scripts]
vis-r = "vis_r.stan_hankel:alma_stan_radial"
