[project]
name = "vis-r"
version = "0.0.1"
dependencies = [
    "numpy", "scipy", "matplotlib", "arviz", "corner",
    "frank", "emcee", "multiprocess", "pytest", "cmdstanpy",
]

[project.scripts]
vis-r = "vis_r.vis_r_emcee_main:run_vis_r_emcee"
